# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proect.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Book_Reader(object):
    def setupUi(self, Book_Reader):
        Book_Reader.setObjectName("Book_Reader")
        Book_Reader.resize(831, 725)
        self.centralwidget = QtWidgets.QWidget(Book_Reader)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 799, 659))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSelect = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSelect.sizePolicy().hasHeightForWidth())
        self.tabSelect.setSizePolicy(sizePolicy)
        self.tabSelect.setObjectName("tabSelect")
        self.message_label = QtWidgets.QLabel(self.tabSelect)
        self.message_label.setGeometry(QtCore.QRect(330, 100, 241, 21))
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabSelect)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 4, 791, 621))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.delete_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        self.delete_button.setFont(font)
        self.delete_button.setAutoDefault(False)
        self.delete_button.setObjectName("delete_button")
        self.gridLayout.addWidget(self.delete_button, 4, 2, 1, 1)
        self.genre_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.genre_comboBox.setObjectName("genre_comboBox")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.genre_comboBox.addItem("")
        self.gridLayout.addWidget(self.genre_comboBox, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 3)
        self.load_text_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        self.load_text_button.setFont(font)
        self.load_text_button.setObjectName("load_text_button")
        self.gridLayout.addWidget(self.load_text_button, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.author_textEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.author_textEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.author_textEdit.setObjectName("author_textEdit")
        self.gridLayout.addWidget(self.author_textEdit, 1, 1, 1, 1)
        self.open_all_books_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.open_all_books_button.setObjectName("open_all_books_button")
        self.gridLayout.addWidget(self.open_all_books_button, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name_textEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_textEdit.setObjectName("name_textEdit")
        self.gridLayout.addWidget(self.name_textEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(128, 128))
        self.label_4.setMaximumSize(QtCore.QSize(128, 128))
        self.label_4.setBaseSize(QtCore.QSize(128, 128))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 3, 1)
        self.tabWidget.addTab(self.tabSelect, "")
        self.tabText = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabText.sizePolicy().hasHeightForWidth())
        self.tabText.setSizePolicy(sizePolicy)
        self.tabText.setObjectName("tabText")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabText)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 611))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.textBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light Condensed")
        self.textBrowser.setFont(font)
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_6.addWidget(self.textBrowser, 1, 0, 1, 4)
        self.background_color_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        self.background_color_button.setFont(font)
        self.background_color_button.setObjectName("background_color_button")
        self.gridLayout_6.addWidget(self.background_color_button, 0, 0, 1, 1)
        self.text_color_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.text_color_button.setObjectName("text_color_button")
        self.gridLayout_6.addWidget(self.text_color_button, 0, 1, 1, 1)
        self.font_style_box = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        self.font_style_box.setFont(font)
        self.font_style_box.setObjectName("font_style_box")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.font_style_box.addItem("")
        self.gridLayout_6.addWidget(self.font_style_box, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.font_size_box = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.font_size_box.setMinimumSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Miriam Mono CLM")
        self.font_size_box.setFont(font)
        self.font_size_box.setMinimum(2)
        self.font_size_box.setMaximum(40)
        self.font_size_box.setProperty("value", 14)
        self.font_size_box.setObjectName("font_size_box")
        self.horizontalLayout.addWidget(self.font_size_box)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.link_open_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.link_open_button.setObjectName("link_open_button")
        self.gridLayout_6.addWidget(self.link_open_button, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tabText, "")
        self.tabAdd = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAdd.sizePolicy().hasHeightForWidth())
        self.tabAdd.setSizePolicy(sizePolicy)
        self.tabAdd.setObjectName("tabAdd")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tabAdd)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 781, 421))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.book_year_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.book_year_label.setObjectName("book_year_label")
        self.gridLayout_7.addWidget(self.book_year_label, 4, 0, 1, 1)
        self.book_link_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.book_link_label.setObjectName("book_link_label")
        self.gridLayout_7.addWidget(self.book_link_label, 5, 0, 1, 1)
        self.load_file_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_file_button.sizePolicy().hasHeightForWidth())
        self.load_file_button.setSizePolicy(sizePolicy)
        self.load_file_button.setMaximumSize(QtCore.QSize(170, 16777215))
        self.load_file_button.setObjectName("load_file_button")
        self.gridLayout_7.addWidget(self.load_file_button, 0, 0, 1, 1)
        self.genre_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.genre_Edit.setObjectName("genre_Edit")
        self.gridLayout_7.addWidget(self.genre_Edit, 3, 1, 1, 1)
        self.status_bar_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.status_bar_label.setText("")
        self.status_bar_label.setObjectName("status_bar_label")
        self.gridLayout_7.addWidget(self.status_bar_label, 6, 1, 1, 1)
        self.book_name_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.book_name_Edit.setObjectName("book_name_Edit")
        self.gridLayout_7.addWidget(self.book_name_Edit, 1, 1, 1, 1)
        self.book_name_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.book_name_label.setObjectName("book_name_label")
        self.gridLayout_7.addWidget(self.book_name_label, 1, 0, 1, 1)
        self.author_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.author_Edit.setObjectName("author_Edit")
        self.gridLayout_7.addWidget(self.author_Edit, 2, 1, 1, 1)
        self.choose_file_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.choose_file_label.setText("")
        self.choose_file_label.setObjectName("choose_file_label")
        self.gridLayout_7.addWidget(self.choose_file_label, 0, 1, 1, 1)
        self.book_genre_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.book_genre_label.setObjectName("book_genre_label")
        self.gridLayout_7.addWidget(self.book_genre_label, 3, 0, 1, 1)
        self.book_author_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.book_author_label.setObjectName("book_author_label")
        self.gridLayout_7.addWidget(self.book_author_label, 2, 0, 1, 1)
        self.year_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.year_Edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.year_Edit.setObjectName("year_Edit")
        self.gridLayout_7.addWidget(self.year_Edit, 4, 1, 1, 1)
        self.add_file_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.add_file_button.setMaximumSize(QtCore.QSize(170, 16777215))
        self.add_file_button.setObjectName("add_file_button")
        self.gridLayout_7.addWidget(self.add_file_button, 6, 0, 1, 1)
        self.link_Edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.link_Edit.setObjectName("link_Edit")
        self.gridLayout_7.addWidget(self.link_Edit, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tabAdd, "")
        Book_Reader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Book_Reader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 26))
        self.menubar.setObjectName("menubar")
        Book_Reader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Book_Reader)
        self.statusbar.setObjectName("statusbar")
        Book_Reader.setStatusBar(self.statusbar)

        self.retranslateUi(Book_Reader)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Book_Reader)

    def retranslateUi(self, Book_Reader):
        _translate = QtCore.QCoreApplication.translate
        Book_Reader.setWindowTitle(_translate("Book_Reader", "Книгочит"))
        self.delete_button.setText(_translate("Book_Reader", "Удалить книгу"))
        self.genre_comboBox.setItemText(0, _translate("Book_Reader", "Любой"))
        self.genre_comboBox.setItemText(1, _translate("Book_Reader", "Роман"))
        self.genre_comboBox.setItemText(2, _translate("Book_Reader", "Комедия"))
        self.genre_comboBox.setItemText(3, _translate("Book_Reader", "Поэма"))
        self.genre_comboBox.setItemText(4, _translate("Book_Reader", "Фэнтэзи"))
        self.genre_comboBox.setItemText(5, _translate("Book_Reader", "Антиутопия"))
        self.genre_comboBox.setItemText(6, _translate("Book_Reader", "Повесть"))
        self.genre_comboBox.setItemText(7, _translate("Book_Reader", "Эпопея"))
        self.genre_comboBox.setItemText(8, _translate("Book_Reader", "Научная фантастика"))
        self.genre_comboBox.setItemText(9, _translate("Book_Reader", "Реализм"))
        self.genre_comboBox.setItemText(10, _translate("Book_Reader", "Философская сказка"))
        self.genre_comboBox.setItemText(11, _translate("Book_Reader", "Документальная проза"))
        self.load_text_button.setText(_translate("Book_Reader", "Открыть книгу"))
        self.label_3.setText(_translate("Book_Reader", "По жанру:"))
        self.open_all_books_button.setText(_translate("Book_Reader", "Показать все книги выбранного жанра"))
        self.label_2.setText(_translate("Book_Reader", "По автору:"))
        self.label.setText(_translate("Book_Reader", "По названию:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelect), _translate("Book_Reader", "Поиск"))
        self.background_color_button.setText(_translate("Book_Reader", "Выбрать цвет фона"))
        self.text_color_button.setText(_translate("Book_Reader", "Выбрать цвет текста"))
        self.font_style_box.setItemText(0, _translate("Book_Reader", "Arial"))
        self.font_style_box.setItemText(1, _translate("Book_Reader", "Arial Black"))
        self.font_style_box.setItemText(2, _translate("Book_Reader", "Bahnschrift"))
        self.font_style_box.setItemText(3, _translate("Book_Reader", "Bahnschrift Light"))
        self.font_style_box.setItemText(4, _translate("Book_Reader", "Bahnschrift SemiBold"))
        self.font_style_box.setItemText(5, _translate("Book_Reader", "Bahnschrift SemiLight"))
        self.font_style_box.setItemText(6, _translate("Book_Reader", "Caladea"))
        self.font_style_box.setItemText(7, _translate("Book_Reader", "Calibri"))
        self.font_style_box.setItemText(8, _translate("Book_Reader", "Cambria"))
        self.font_style_box.setItemText(9, _translate("Book_Reader", "Candara"))
        self.font_style_box.setItemText(10, _translate("Book_Reader", "Carlito"))
        self.font_style_box.setItemText(11, _translate("Book_Reader", "Comic Sans MS"))
        self.font_style_box.setItemText(12, _translate("Book_Reader", "Constantia"))
        self.font_style_box.setItemText(13, _translate("Book_Reader", "Corbel"))
        self.font_style_box.setItemText(14, _translate("Book_Reader", "Courier New"))
        self.font_style_box.setItemText(15, _translate("Book_Reader", "DejaVu Serif"))
        self.font_style_box.setItemText(16, _translate("Book_Reader", "Fixedsys"))
        self.font_style_box.setItemText(17, _translate("Book_Reader", "Frank Ruehl CLM"))
        self.font_style_box.setItemText(18, _translate("Book_Reader", "Gadugi"))
        self.font_style_box.setItemText(19, _translate("Book_Reader", "Ink Free"))
        self.font_style_box.setItemText(20, _translate("Book_Reader", "KacstBook"))
        self.font_style_box.setItemText(21, _translate("Book_Reader", "Microsoft JhengHei"))
        self.font_style_box.setItemText(22, _translate("Book_Reader", "OpenSymbol"))
        self.font_style_box.setItemText(23, _translate("Book_Reader", "Reem Kufi"))
        self.font_style_box.setItemText(24, _translate("Book_Reader", "Segoe Print"))
        self.font_style_box.setItemText(25, _translate("Book_Reader", "Source Code Pro Medium"))
        self.font_style_box.setItemText(26, _translate("Book_Reader", "Times New Roman"))
        self.font_style_box.setItemText(27, _translate("Book_Reader", "Yu Gothic Medium"))
        self.link_open_button.setText(_translate("Book_Reader", "Открыть ссылку на книгу в браузере"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabText), _translate("Book_Reader", "Текст книги"))
        self.book_year_label.setText(_translate("Book_Reader", "Год написания"))
        self.book_link_label.setText(_translate("Book_Reader", "Ссылка"))
        self.load_file_button.setText(_translate("Book_Reader", "Загрузить файл"))
        self.book_name_label.setText(_translate("Book_Reader", "Название книги*"))
        self.book_genre_label.setText(_translate("Book_Reader", "Жанр"))
        self.book_author_label.setText(_translate("Book_Reader", "Автор*"))
        self.add_file_button.setText(_translate("Book_Reader", "Сохранить новую книгу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdd), _translate("Book_Reader", "Добавление книги"))
